feat: CommitLint + Husky test 5

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,9 +1,9 @@
 #!/usr/bin/env sh
 if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Commit abortado. A tag do seu commit está inválida." >&2
+    printf "\n\e[0;31mCommit abortado. A \e[1;34mTAG\e[0m\e[0;31m do seu commit está inválida.\n\n\e[0m" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
-    echo "Commit abortado. A mensagem do seu commit está muito longa (mais de 88 caracteres)."
+    printf "\n\e[0;31mCommit abortado. A\e[1;34m MENSAGEM \e[0m\e[0;31mdo seu commit está muito longa \e[0m\e[1;34m(mais de 88 caracteres). \e[0m\n" >&2
     exit 1
 fi
